### ISSUE TITLE
function in class `crc` are not constexpr

### ISSUE THREAD

**Issue by CrustyAuklet** [AshleyRoll/crc_cpp#16]
First of all, I went to your talk (virtually) at cppcon and I really enjoyed it and this library is really great. I have many legacy IOT message formats that use really "unique" polynomials and starting values, so often it is a real pain to use other libraries. Yours was very easy to specialize for our CRCs.

The issue I am running into is that I can't use the `crc` class in a constant expression. This seems to be a simple oversight, since to fix it I just mark all the functions in that class `constexpr`. I can also see how it was missed because all my code worked until this morning! I have no idea what changed, I just renamed some files, but now it won't compile unless I make those functions contexpr.

Here is a minimal example [godbolt](https://godbolt.org/z/x3ETMdcs4):
```c++
#include <https://raw.githubusercontent.com/AshleyRoll/crc_cpp/main/include/crc_cpp.h>
#include <span>

constexpr bool check_message(std::span<const uint8_t> data, const uint8_t expected) {
    // CRC for upper half is header + first 4 sats and is in byte 14
    crc_cpp::crc8 crc;
    for(const auto b : data) {
        crc.update(b);
    }
    return expected == crc.final();
}
```
compiler output:
```
<source>: In function 'constexpr bool check_message(std::span<const unsigned char>, uint8_t)':
<source>:10:33: error: call to non-'constexpr' function 'crc_cpp::impl::crc<TAlgorithm, TABLE_SIZE>::accumulator_type crc_cpp::impl::crc<TAlgorithm, TABLE_SIZE>::final() [with TAlgorithm = crc_cpp::impl::crc_algorithm<unsigned char, 7, 0, 0, false>; crc_cpp::table_size TABLE_SIZE = crc_cpp::table_size::small; crc_cpp::impl::crc<TAlgorithm, TABLE_SIZE>::accumulator_type = unsigned char]'
https://raw.githubusercontent.com/AshleyRoll/crc_cpp/main/include/crc_cpp.h:410:44: note: 'crc_cpp::impl::crc<TAlgorithm, TABLE_SIZE>::accumulator_type crc_cpp::impl::crc<TAlgorithm, TABLE_SIZE>::final() [with TAlgorithm = crc_cpp::impl::crc_algorithm<unsigned char, 7, 0, 0, false>; crc_cpp::table_size TABLE_SIZE = crc_cpp::table_size::small; crc_cpp::impl::crc<TAlgorithm, TABLE_SIZE>::accumulator_type = unsigned char]' declared here
Compiler returned: 1
```

**Comment by AshleyRoll** [comment]
Hi @CrustyAuklet Thanks for the bug report. Glad you enjoyed my CppCon talk! Very happy that you found my my library useful!

I'll have a look at this after Christmas. It shouldn't be too hard to fix (at least for C++20, not sure about 17 support).

**Comment by AshleyRoll** [comment]
I was able to make this work for both C++20 and C++17. Thanks for the bug report @CrustyAuklet
